### PR TITLE
LRDOCS-4636, Custom Configuration UIs

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-4636, Merry Christmas Neal. Best gift you've ver received, undoubtedly. cc @drewbrokke.

### CODE REVIEW

**Comment by rbohl** [comment]
bump

**Comment by nealrobbins** [comment]
> bump

Kissed this on its way weeks ago. Forgot to close pull request. Sorry.

**Comment by rbohl** [comment]
It's a best practice (that we usually but don't always follow) to link to the forwarded PR so someone can follow the chain to find the most recent pull. 

However, I see it hasn't been published and didn't notice it in Rich's queue.

**Comment by rbohl** [comment]
Oh, there it is, missed it the first time: https://github.com/sez11a/liferay-docs/pull/3807

**Pull request closed without merging**
